### Create An Account
POST {{host}}/api/register
Accept: application/json
Content-Type: application/json

{
    "name": "John Doe",
    "email": "infinitypaul3@live.com",
    "password": "Password_#1",
    "password_confirmation": "Password_#1",
    "username": "infinitypaul3"

}
> {% client.global.set("token", response.body.access_token) %}

### Login
POST {{host}}/api/login
Accept: application/json
Content-Type: application/json

{
    "email": "infinitypaul@live.com",
    "password": "Password_#1"
}
> {% client.global.set("token", response.body.access_token) %}

### Create Task
POST {{host}}/api/tasks
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "New Task"
}

### Update Task
PUT {{host}}/api/tasks/4
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Updated Task"
}

### Delete Task
DELETE {{host}}/api/tasks/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Get All Tasks
GET {{host}}/api/tasks
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Get Single Task
GET {{host}}/api/tasks/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### Mark Task As Completed Or Incomplete
POST {{host}}/api/tasks/mark/4
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


